<?php

namespace EmailMarketing\General\Filter;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-07-31 at 11:57:43.
 */
class FilterOpeningTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var FilterOpening
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new FilterOpening;
	}

	/**
	 * @expectedException InvalidArgumentException
	 */
	public function testObjectIsNotAllowed()
	{
		$this->object->setObject('');
	}
	
	/**
	 * Generación de SQL cuando no ha abierto el correo y es ALL multiple
	 */
	public function testGetFromForNegativeAndRequiredMore() {
		$object = new \stdClass();
		$object->idMail = 45;
		$object->negative = true;
		$object->required = true;
		$object->more = true;
		
		$this->object->setObject($object);
		$this->object->createSQL();
		
		$from = $this->object->getFrom();
		$expectedF = " JOIN mxc AS mc45 ON (mc45.idContact = c.idContact AND mc45.idMail = 45 AND mc45.opening = 0) ";
		
		$where = $this->object->getWhere();
		$expectedW = "";
		
		$this->assertEquals($expectedF, $from, 'Generación de FROM_SQL cuando no ha abierto el correo y es ALL multiple');
		$this->assertEquals($expectedW, $where, 'Generación de WHERE_SQL cuando no ha abierto el correo y es ALL multiple');
	}
	
	/**
	 * Generación de SQL cuando ha abierto el correo y es ALL único
	 */
	public function testGetFromForPositiveAndRequiredNoMore() {
		$object = new \stdClass();
		$object->idMail = 45;
		$object->negative = false;
		$object->required = true;
		$object->more = false;
		
		$this->object->setObject($object);
		$this->object->createSQL();
		$from = $this->object->getFrom();
		
		$expected = " JOIN mxc AS mc45 ON (mc45.idContact = c.idContact AND mc45.idMail = 45 AND mc45.opening != 0) ";
		$this->assertEquals($expected, $from, 'Generación de SQL cuando ha abierto el correo y es ALL único');
	}
	
	/**
	 * Generación de SQL cuando no ha abierto el correo y es ANY único
	 */
	public function testGetFromForNegativeAndNoRequiredNoMore() {
		$object = new \stdClass();
		$object->idMail = 45;
		$object->negative = true;
		$object->required = false;
		$object->more = false;
		
		$this->object->setObject($object);
		$this->object->createSQL();
		$from = $this->object->getFrom();
		
		$expected = " JOIN mxc AS mc45 ON (mc45.idContact = c.idContact AND mc45.idMail = 45 AND mc45.opening = 0) ";
		$this->assertEquals($expected, $from, 'Generación de SQL cuando no ha abierto el correo y es ANY único');
	}
	
	/**
	 * Generación de SQL cuando no ha abierto el correo y es ANY multiple
	 */
	public function testGetFromForNegativeAndNoRequiredMore() {
		$object = new \stdClass();
		$object->idMail = 45;
		$object->negative = true;
		$object->required = false;
		$object->more = true;
		
		$this->object->setObject($object);
		$this->object->createSQL();
		$from = $this->object->getFrom();
		
		$expected = " LEFT JOIN mxc AS mc45 ON (mc45.idContact = c.idContact AND mc45.idMail = 45 AND mc45.opening = 0) ";
		$this->assertEquals($expected, $from, 'Generación de SQL cuando no ha abierto el correo y es ANY multiple');
	}
	
	/**
	 * 
	 */
//	public function testGetWhereForNegativeAndNoRequiredMore() {
//		$object = new \stdClass();
//		$object->idMail = 45;
//		$object->negative = true;
//		$object->required = true;
//		$object->more = true;
//		
//		$this->object->setObject($object);
//		$this->object->createSQL();
//		$from = $this->object->getFrom();
//		$where = $this->object->getWhere();
//		
//		$expectedF = " JOIN mxc AS mc45 ON (mc45.idContact = c.idContact AND mc45.idMail = 45 AND mc45.opening = 0) ";
//		$expectedW = " JOIN mxc AS mc45 ON (mc45.idContact = c.idContact AND mc45.idMail = 45 AND mc45.opening = 0) ";
//		
//		$this->assertEquals($expectedF, $from, 'Generación de SQL FROM cuando no ha abierto el correo y es ALL');
//		$this->assertEquals($expectedW, $where, 'Generación de SQL WHERE cuando no ha abierto el correo y es ALL');
//	}
	
//	public function testGetWhereForNegative() {
//		$object = new \stdClass();
//		$object->idMail = 45;
//		$object->negative = true;
//		$object->required = true;
//		
//		$this->object->setObject($object);
//		$this->object->createSQL();
//		$from = $this->object->getFrom();
//		
//		$expected = " JOIN mxc AS mc45 ON (mc45.idContact = c.idContact AND mc45.idMail = 45 AND mc45.opening = 0) ";
//		$this->assertEquals($expected, $from, 'Generación de SQL cuando no ha abierto el correo y es ALL');
//	}
}
