<?php

namespace EmailMarketing\General\Filter;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-08-01 at 10:19:55.
 */
class FilterSentTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var FilterSent
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new FilterSent;
	}
	
	/**
	 * @expectedException InvalidArgumentException
	 */
	public function testObjectIsNotAllowed()
	{
		$this->object->setObject('');
	}
	
	/**
	 * Que hayan recibido el correo 45 (Sin más filtros) condición AND
	 */
	public function testSentOneFilterConditionAll() {
		$object = new \stdClass();
		$object->idMail = 45;
		$object->required = true;
		$object->more = false;
		$object->negative = false;
		
		$this->object->setObject($object);
		$this->object->createSQL();
		
		$from = $this->object->getFrom();
		$expectedF = " JOIN mxc AS mc45 ON (mc45.idContact = c.idContact AND mc45.idMail = 45) ";
		
		$where = $this->object->getWhere();
		$expectedW = "";
		
		$this->assertEquals($expectedF, $from, 'FROM_SQL Que hayan recibido el correo 45 (Sin más filtros) condición AND');
		$this->assertEquals($expectedW, $where, 'WHERE_SQL Que hayan recibido el correo 45 (Sin más filtros) condición AND');
	}
	
	/**
	 * Que hayan recibido el correo 45 (Con más filtros) condición AND
	 */
	public function testSentMuchFilterConditionAll() {
		$object = new \stdClass();
		$object->idMail = 45;
		$object->required = true;
		$object->more = true;
		$object->negative = false;
		
		$this->object->setObject($object);
		$this->object->createSQL();
		
		$from = $this->object->getFrom();
		$expectedF = " JOIN mxc AS mc45 ON (mc45.idContact = c.idContact AND mc45.idMail = 45) ";
		
		$where = $this->object->getWhere();
		$expectedW = "";
		
		$this->assertEquals($expectedF, $from, 'FROM_SQL Que hayan recibido el correo 45 (Con más filtros) condición AND');
		$this->assertEquals($expectedW, $where, 'WHERE_SQL Que hayan recibido el correo 45 (Con más filtros) condición AND');
	}
	
	/**
	 * Que hayan recibido el correo 45 (Sin más filtros) condición OR
	 */
	public function testSentOneFilterConditionAny() {
		$object = new \stdClass();
		$object->idMail = 45;
		$object->required = false;
		$object->more = false;
		$object->negative = false;
		
		$this->object->setObject($object);
		$this->object->createSQL();
		
		$from = $this->object->getFrom();
		$expectedF = " JOIN mxc AS mc45 ON (mc45.idContact = c.idContact AND mc45.idMail = 45) ";
		
		$where = $this->object->getWhere();
		$expectedW = "";
		
		$this->assertEquals($expectedF, $from, 'FROM_SQL Que hayan recibido el correo 45 (Sin más filtros) condición OR');
		$this->assertEquals($expectedW, $where, 'WHERE_SQL Que hayan recibido el correo 45 (Sin más filtros) condición OR');
	}
	
	/**
	 * Que hayan recibido el correo 45 (Con más filtros) condición OR
	 */
	public function testSentMuchFilterConditionAny() {
		$object = new \stdClass();
		$object->idMail = 45;
		$object->required = false;
		$object->more = true;
		$object->negative = false;
		
		$this->object->setObject($object);
		$this->object->createSQL();
		
		$from = $this->object->getFrom();
		$expectedF = " LEFT JOIN mxc AS mc45 ON (mc45.idContact = c.idContact AND mc45.idMail = 45) ";
		
		$where = $this->object->getWhere();
		$expectedW = " mc45.idContact IS NOT NULL ";
		
		$this->assertEquals($expectedF, $from, 'FROM_SQL Que hayan recibido el correo 45 (Con más filtros) condición OR');
		$this->assertEquals($expectedW, $where, 'WHERE_SQL Que hayan recibido el correo 45 (Con más filtros) condición OR');
	}
	
	
	/**
	 * Que no hayan recibido el correo 45 (sin más filtros) condición AND
	 */
	public function testSentOneFilterConditionAllNegative() {
		$object = new \stdClass();
		$object->idMail = 45;
		$object->required = true;
		$object->more = false;
		$object->negative = true;
		
		$this->object->setObject($object);
		$this->object->createSQL();
		
		$from = $this->object->getFrom();
		$expectedF = " LEFT JOIN mxc AS mc45 ON (mc45.idContact = c.idContact AND mc45.idMail = 45) ";
		
		$where = $this->object->getWhere();
		$expectedW = " mc45.idContact IS NULL ";
		
		$this->assertEquals($expectedF, $from, 'FROM_SQL Que no hayan recibido el correo 45 (sin más filtros) condición AND');
		$this->assertEquals($expectedW, $where, 'WHERE_SQL Que no hayan recibido el correo 45 (sin más filtros) condición AND');
	}

	/**
	 * Que no hayan recibido el correo 45 (con más filtros) condición AND
	 */
	public function testSentMuchFilterConditionAllNegative() {
		$object = new \stdClass();
		$object->idMail = 45;
		$object->required = true;
		$object->more = true;
		$object->negative = true;
		
		$this->object->setObject($object);
		$this->object->createSQL();
		
		$from = $this->object->getFrom();
		$expectedF = " LEFT JOIN mxc AS mc45 ON (mc45.idContact = c.idContact AND mc45.idMail = 45) ";
		
		$where = $this->object->getWhere();
		$expectedW = " mc45.idContact IS NULL ";
		
		$this->assertEquals($expectedF, $from, 'FROM_SQL Que no hayan recibido el correo 45 (sin más filtros) condición AND');
		$this->assertEquals($expectedW, $where, 'WHERE_SQL Que no hayan recibido el correo 45 (sin más filtros) condición AND');
	}
	
	/**
	 * Que no hayan recibido el correo 45 (sin más filtros) condición OR
	 */
	public function testSentOneFilterConditionAnyNegative() {
		$object = new \stdClass();
		$object->idMail = 45;
		$object->required = false;
		$object->more = false;
		$object->negative = true;
		
		$this->object->setObject($object);
		$this->object->createSQL();
		
		$from = $this->object->getFrom();
		$expectedF = " LEFT JOIN mxc AS mc45 ON (mc45.idContact = c.idContact AND mc45.idMail = 45) ";
		
		$where = $this->object->getWhere();
		$expectedW = " mc45.idContact IS NULL ";
		
		$this->assertEquals($expectedF, $from, 'FROM_SQL Que no hayan recibido el correo 45 (sin más filtros) condición AND');
		$this->assertEquals($expectedW, $where, 'WHERE_SQL Que no hayan recibido el correo 45 (sin más filtros) condición AND');
	}
	
	/**
	 * Que no hayan recibido el correo 45 (con más filtros) condición OR
	 */
	public function testSentMuchFilterConditionAnyNegative() {
		$object = new \stdClass();
		$object->idMail = 45;
		$object->required = false;
		$object->more = true;
		$object->negative = true;
		
		$this->object->setObject($object);
		$this->object->createSQL();
		
		$from = $this->object->getFrom();
		$expectedF = " LEFT JOIN mxc AS mc45 ON (mc45.idContact = c.idContact AND mc45.idMail = 45) ";
		
		$where = $this->object->getWhere();
		$expectedW = " mc45.idContact IS NULL ";
		
		$this->assertEquals($expectedF, $from, 'FROM_SQL Que no hayan recibido el correo 45 (sin más filtros) condición AND');
		$this->assertEquals($expectedW, $where, 'WHERE_SQL Que no hayan recibido el correo 45 (sin más filtros) condición AND');
	}
}