<?php

namespace EmailMarketing\General\Misc;

//use \EmailMarketing\General\Misc\TotalTimePeriod;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-05-13 at 09:48:51.
 */
class TotalTimePeriodTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var TimePeriod
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new TotalTimePeriod;
	}

	
	public function testComplete()
	{
		$data = array(1399663088, 1399139892, 1397747792, 1398212638, 1397356848, 1395144528, 1397963811);
		$this->object->setData($data);
//		$this->object->setPeriodStart($start);
		$this->object->processTimePeriod();
		
		var_dump($this->object->getTimePeriod());
		$this->assertEquals(7, $this->object->getTotal());
	}
	/**
	 * @covers EmailMarketing\General\Misc\TimePeriod::getTotal
	 * @todo   Implement testGetTotal().
	 */
	public function testGetTotal() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}
